# SPDX-FileCopyrightText:  Copyright 2023 Roland Csaszar
# SPDX-License-Identifier: MIT
#
# Project:  vscode-scheme-repl
# File:     release.yml
# Date:     14.May.2023
#
# ==============================================================================

name: Release

on:
    release:
        types: [created]

    push:
        tags:
            - "v*.*.*"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    package:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Get Tag
              uses: olegtarasov/get-tag@v2.1.2
              id: tagName
              with:
                  tagRegex: "v(.*)"

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Generate Changelog
              run: |
                  yarn --ignore-engines install --dev
                  yarn --ignore-engines ts-node generate_changelog.ts ${{ env.GIT_TAG_NAME }}

            - name: Build VSIX
              run: yarn --ignore-engines package

            - name: Release to GitHub
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  name: Version ${{ env.GIT_TAG_NAME }}
                  body_path: latest_changelog.md
                  files: ./vscode-scheme-repl*.vsix
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/upload-artifact@v3
              if: ${{ always() }}
              with:
                  name: Expect and Inline Test Explorer
                  path: ./vscode-scheme-repl*.vsix
